export interface Notification {
  id: string;
  notificationid?: string | null;
  notification_group?: string | null;
  ref_chatid?: string | null;
  ref_chat_url?: string | null;
  role?: string | null;
  content?: string | null;
  content_json?: Record<string, unknown> | null;
  createdAt: string;
  favorite?: boolean;
  islike?: boolean;
  bookmark?: boolean;
  custom_one?: string | null;
  custom_two?: string | null;
  user_id?: string | null;
  user_name?: string | null;
  user_email?: string | null;
  status?: string | null;
  mydoc_list_id?: string | null;
  mydoc_number?: string | null;
  response_data_json?: Record<string, unknown> | null;
  response_file_url?: string | null;
  columns?: Record<string, unknown> | null;
  chartconfig?: Record<string, unknown> | null;
  plan_id?: string | null;
  plan_code?: string | null;
  task_id?: string | null;
  task_code?: string | null;
  msg_id?: string | null;
  msg_code?: string | null;
  prompt_json?: Record<string, unknown> | null;
  chat_session?: string | null;
  response_story_json?: Record<string, unknown> | null;
  response_narrative_json?: Record<string, unknown> | null;
  response_file_json?: Record<string, unknown> | null;
  response_text_json?: Record<string, unknown> | null;
  custom_one_json?: Record<string, unknown> | null;
  custom_two_json?: Record<string, unknown> | null;
  remainder?: boolean;
  important?: boolean;
  progress_status?: string | null;
  created_user_id?: string | null;
  created_user_name?: string | null;
  ref_user_id?: string | null;
  ref_user_name?: string | null;
  created_date?: string | null;
  updated_date?: string | null;
  data_source_name?: string | null;
  chat_message_type?: string | null;
  soc_room_id?: string | null;
  sender_id?: string | null;
  sender_user_name?: string | null;
  receiver_user_id?: string | null;
  receiver_user_name?: string | null;
  receiver_group_id?: string | null;
  ref_chat_message_json?: Record<string, unknown> | null;
  ref_chat_message_id?: string | null;
  chat_message?: string | null;
  from_chat_group_name?: string | null;
  to_chat_group_name?: string | null;
  from_agent_name?: string | null;
  to_agent_name?: string | null;
  from_json?: Record<string, unknown> | null;
  to_json?: Record<string, unknown> | null;
  from_business_number?: string | null;
  from_business_name?: string | null;
  to_business_number?: string | null;
  to_business_name?: string | null;
  for_business_number?: string | null;
  for_business_name?: string | null;
  ref_business_number?: string | null;
  ref_business_name?: string | null;
  receiver_display_name?: string | null;
  chat_group_name?: string | null;
  chat_group_code?: string | null;
  chat_group_type?: string | null;
  chat_group_category?: string | null;
  room_type?: string | null;
  room_group?: string | null;
  room_name?: string | null;
  room_code?: string | null;
  progress_json?: Record<string, unknown> | null;
  status_log_json?: Record<string, unknown> | null;
  user_log_json?: Record<string, unknown> | null;
  business_log_json?: Record<string, unknown> | null;
  agent_json?: Record<string, unknown> | null;
  response_json?: Record<string, unknown> | null;
  timeline_json?: Record<string, unknown> | null;
  file_upload_json?: Record<string, unknown> | null;
  share_json?: Record<string, unknown> | null;
  message_loop_json?: Record<string, unknown> | null;
  message_content_json?: Record<string, unknown> | null;
  message_card_json?: Record<string, unknown> | null;
  replied_to_message_id?: string | null;
  related_to_message_id?: string | null;
  forwarded_from_message_id?: string | null;
  seen_by_users?: Record<string, unknown> | null;
  reactions?: Record<string, unknown> | null;
  sender_display_name?: string | null;
  attachment_url?: string | null;
  attachment_name?: string | null;
  chat_message_opened?: boolean;
  attachment_type?: string | null;
  is_forwarded?: boolean;
  selected_users?: Record<string, unknown> | null;
  forwared_message?: string | null;
  forwarded_message_id?: string | null;
  forwared_by_user_id?: string | null;
  forwared_date?: string | null;
  forwared_by_user_name?: string | null;
  chat_group?: Record<string, unknown> | null;
  email_id?: string | null;
  doc_id?: string | null;
  toolinvocations?: Record<string, unknown> | null;
  parts?: Record<string, unknown> | null;
  usage?: Record<string, unknown> | null;
  business_name?: string | null;
  business_number?: string | null;
  charttype?: string | null;
  chartdata?: Record<string, unknown> | null;
  chartoptions?: Record<string, unknown> | null;
  text?: string | null;
  story_json?: Record<string, unknown> | null;
  db_connection_json?: Record<string, unknown> | null;
  selected_form_id?: string | null;
  table_columns?: Record<string, unknown> | null;
  chart?: Record<string, unknown> | null;
  api_connection_json?: Record<string, unknown> | null;
  story_api?: string | null;
  read_status?: boolean;
  archive_status?: boolean;
  cards?: Record<string, unknown> | null;
  created_at?: string | null;
  updated_at?: string | null;
  deleted_at?: string | null;
  group_id?: string | null;
  toolinvocations2?: Record<string, unknown> | null;
  analysisprompt?: string | null;
  suggestions?: Record<string, unknown> | null;
  initialmsg?: string | null;
  jsondata?: Record<string, unknown> | null;
  assistantid?: string | null;
  attachments_json?: Record<string, unknown> | null;
  prompt_tokens?: number | null;
  completion_tokens?: number | null;
  total_tokens?: number | null;
  prompt_uuid?: string | null;
}

